#!/bin/sh

cd "$(dirname "$0")"
set -e

rm -rf css
mkdir css

# Install clean-css and clean-css-cli
npm install


# Generate examples/normalize.css from src/Css/Normalize.elm
cd ../examples && elm-package install && elm-css Stylesheets.elm && cd ../tests


# Clean and beautify css/normalize.css
node_modules/.bin/cleancss -O1 specialComments:off --format keep-breaks -o css/normalize.min.css ../examples/normalize.css


# Download normalize.css from https://github.com/necolas/normalize.css
curl -o css/necolas.normalize.css https://raw.githubusercontent.com/necolas/normalize.css/master/normalize.css
# Clean and beautify css/necolas.normalize.css
node_modules/.bin/cleancss -O1 specialComments:off --format keep-breaks -o css/necolas.normalize.min.css css/necolas.normalize.css


# Compare css/normalize.min.css with css/necolas.normalize.min.css
echo "Comparing styles generated by Elm with styles at"
echo "https://raw.githubusercontent.com/necolas/normalize.css/master/normalize.css"
echo ""

if sdiff -s -w 80 css/normalize.min.css css/necolas.normalize.min.css; then
  echo "\033[33;32m Success: the files are identical."
else
  echo ""
  echo "\033[33;31m Failed: there were some differences."
fi


rm -rf css
